;; 1a. DATA DEFINITIONS
;; 1b. CONSTANT DEFINITIONS
;; 1c. FUNCTION WISH LIST
;; NAME:
;; SIGNATURE:
;; PURPOSE STATEMENT:
;; 2a. FUNCTION SIGNATURE:
;; 2b. PURPOSE STATEMENT:
;; 2c. HEADER
;; 3a. FUNCTIONAL EXAMPLES
;; Given: , Expect:
;; 3b. TESTS
;; 4. TEMPLATE
;; 5. CODE